package com.jantiojo.xpaysdk.module.device

enum class XPayTamperReason {
    NONE,
    K21_BUTTON_BATTERY_DEAD,
    K21_TAMPER_5_TRIGGERED,
    K21_TAMPER_2_TRIGGERED,
    K21_TAMPER_0_TRIGGERED,
    K21_TAMPER_1_TRIGGERED,
    CHIP_1902_TAMPER_2_TRIGGERED,
    CHIP_1902_TAMPER_0_TRIGGERED,
    CHIP_1902_TAMPER_1_TRIGGERED,
    CHIP_1902_TAMPER_3_TRIGGERED,
    CHIP_3682_TAMPER_4_TRIGGERED,
    CHIP_3682_TAMPER_5_TRIGGERED,
    CHIP_3652_BUTTON_BATTERY_DEAD,
    ANTI_CUTTING_MACHINE_AUTH_FAILED,
    NO_ANTI_CUTTING_MACHINE_AUTH,
    P2D_AUTH_FAILED,
    D2P_AUTH_FAILED;
}