package com.jantiojo.xpaysdk

enum class XPayModuleType {
    BEEPER,
    CARD_READER,
    CRYPTO,
    KEY_MANAGER,
    PIN_ENTRY,
    DEVICE_MANAGER,
    LED,
    PRINTER,
    BARCODE_DECODER,
    ROUTE_MANAGER,
    SETTINGS,
    CASH_BOX,
    ETHERNET_MANAGER,
    SERIAL_PORT_MANAGER,
    BARCODE_SCANNER,
    DEVICE_STATISTICS_MANAGER,
    RECOVERY,
    BOOT_PROVIDER,
}