package com.jantiojo.xpaysdk

enum class XPayModuleType {
    BEEPER,
    CARD_READER,
    CRYPTO,
    KEY_MANAGER,
    PIN_ENTRY,
    DEVICE_MANAGER,
    LED,
    PRINTER,
    BARCODE_DECODER,
    ROUTE_MANAGER,
    SETTINGS,
    EMV_L2_SERVICE,
    CASH_BOX,
    FUTUREX,
    ETHERNET_MANAGER,
    SERIAL_PORT_MANAGER,
    BARCODE_SCANNER
}